// Code generated by protoc-gen-go-setters. DO NOT EDIT.
// source: example/example.proto
package example

import (
	anypb "google.golang.org/protobuf/types/known/anypb"
)

func (x *Example_Bar) SetNested(in string) {
	x.Nested = in
}

func (x *Example_Far) SetActive(in bool) {
	x.Active = in
}

func (x *Example) SetAbc(in string) {
	x.AbcOneof = &Example_Abc{Abc: in}
}

func (x *Example) SetFar(in *Example_Far) {
	x.AbcOneof = &Example_Far_{Far: in}
}

func (x *Example) SetName(in string) {
	x.Name = in
}

func (x *Example) SetCount(in int32) {
	x.Count = in
}

func (x *Example) SetActive(in bool) {
	x.Active = in
}

func (x *Example) SetTags(in []string) {
	x.Tags = in
}

func (x *Example) AppendTags(in ...string) {
	x.Tags = append(x.Tags, in...)
}

func (x *Example) SetFoo(in *Foo) {
	x.Foo = in
}

func (x *Example) SetBar(in *Example_Bar) {
	x.Bar = in
}

func (x *Example) SetAny(in *anypb.Any) {
	x.Any = in
}

func (x *Example) SetData(in Data) {
	x.Data = in
}

func (x *Example) SetExtraComments(in *string) {
	x.ExtraComments = in
}

func (x *Example) SetFooMap(in map[string]*Foo) {
	x.FooMap = in
}

func (x *Example) SetFooMapKey(key string, val *Foo) {
	x.FooMap[key] = val
}

func (x *Example) SetSample(in *SampleMessage) {
	x.Sample = in
}

func (x *Foo) SetCount(in int64) {
	x.Count = in
}

func (x *Funk) SetCount(in int64) {
	x.Count = in
}

func (x *SampleMessage) SetName(in string) {
	x.TestOneof = &SampleMessage_Name{Name: in}
}

func (x *SampleMessage) SetFoo(in *Foo) {
	x.TestOneof = &SampleMessage_Foo{Foo: in}
}

func (x *SampleMessage) SetFunk(in *Funk) {
	x.TestOneof = &SampleMessage_Funk{Funk: in}
}
